In [5]:
import sys
import os 
sys.path.append("..")

In [6]:
from src.llm_client import call_llm
from src.embeddings import (
    embed_dataframe,
    get_embedding
)

In [7]:
import pandas as pd
df_embeddings = pd.read_csv("../data/raw/homenest_reviews.csv")
df_embeddings

,review_id,product_category,product_name,review_text,star_rating,review_date,verified_purchase
0,1,Bedroom Furniture,DreamRest Memory Foam Mattress,My DreamRest Memory Foam Mattress arrived well...,5,2024-02-08,False
1,2,Kitchen Appliances,InstaBrew Coffee Maker,The InstaBrew Coffee Maker itself is fine but ...,2,2023-09-11,False
2,3,Living Room,GlowLight Floor Lamp,My GlowLight Floor Lamp arrived well packaged ...,5,2023-07-03,False
3,4,Living Room,CozySofa L-Shape Sectional,The CozySofa L-Shape Sectional is okay. Does w...,3,2023-06-30,True
4,5,Kitchen Appliances,TurboBlend Pro 5000,Delivery took 3 weeks and the TurboBlend Pro 5...,3,2024-09-23,True
...,...,...,...,...,...,...,...
4995,4996,Bedroom Furniture,NightOwl LED Bedside Lamp,My NightOwl LED Bedside Lamp arrived well pack...,5,2024-05-01,True
4996,4997,Bedroom Furniture,DreamRest Memory Foam Mattress,The DreamRest Memory Foam Mattress arrived on ...,3,2023-06-09,False
4997,4998,Living Room,GlowLight Floor Lamp,Great product. The GlowLight Floor Lamp exceed...,5,2023-07-15,True
4998,4999,Living Room,AirPurifier ProMax,Five stars. The AirPurifier ProMax is well bui...,5,2024-12-18,True
4999,5000,Living Room,GlowLight Floor Lamp,Best purchase I made this year. The GlowLight ...,5,2023-04-06,False

In [8]:
import re

def clean_for_embedding(text):

    if not isinstance(text, str):
        return ""

    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [10]:
df_embeddings.apply(clean_for_embedding)
df_embeddings

,review_id,product_category,product_name,review_text,star_rating,review_date,verified_purchase
0,1,Bedroom Furniture,DreamRest Memory Foam Mattress,My DreamRest Memory Foam Mattress arrived well...,5,2024-02-08,False
1,2,Kitchen Appliances,InstaBrew Coffee Maker,The InstaBrew Coffee Maker itself is fine but ...,2,2023-09-11,False
2,3,Living Room,GlowLight Floor Lamp,My GlowLight Floor Lamp arrived well packaged ...,5,2023-07-03,False
3,4,Living Room,CozySofa L-Shape Sectional,The CozySofa L-Shape Sectional is okay. Does w...,3,2023-06-30,True
4,5,Kitchen Appliances,TurboBlend Pro 5000,Delivery took 3 weeks and the TurboBlend Pro 5...,3,2024-09-23,True
...,...,...,...,...,...,...,...
4995,4996,Bedroom Furniture,NightOwl LED Bedside Lamp,My NightOwl LED Bedside Lamp arrived well pack...,5,2024-05-01,True
4996,4997,Bedroom Furniture,DreamRest Memory Foam Mattress,The DreamRest Memory Foam Mattress arrived on ...,3,2023-06-09,False
4997,4998,Living Room,GlowLight Floor Lamp,Great product. The GlowLight Floor Lamp exceed...,5,2023-07-15,True
4998,4999,Living Room,AirPurifier ProMax,Five stars. The AirPurifier ProMax is well bui...,5,2024-12-18,True
4999,5000,Living Room,GlowLight Floor Lamp,Best purchase I made this year. The GlowLight ...,5,2023-04-06,False